import zstandard as zstd
import io, json, hashlib
from concurrent.futures import ProcessPoolExecutor
from tqdm import tqdm


def starcoder_basic_filter(text):
    lines = text.split("\n")
    n = len(text)
    if n == 0 or n > 1_000_000:                            return False
    if len(lines) > 100_000:                               return False
    if max((len(l) for l in lines), default=0) > 1000:     return False
    if sum(len(l) for l in lines)/max(len(lines),1) > 100: return False
    # single pass for alpha + hex instead of two full char loops
    alpha = hexc = 0
    for c in text:
        if c.isalpha(): alpha += 1
        if c in "0123456789abcdefABCDEF": hexc += 1
    if alpha/n < 0.25:  return False
    if hexc/n > 0.25:   return False
    head = "\n".join(lines[:5]).lower()
    if any(k in head for k in ("auto-generated","autogenerated",
            "automatically generated","generated automatically","this file is generated")):
        return False
    return True

def tex_filter(text):
    n = len(text); lines = text.split("\n")
    if n == 0 or n > 1_000_000:        return False   # keep size cap
    if len(lines) > 100_000:           return False
    head = "\n".join(lines[:5]).lower()
    if any(k in head for k in ("auto-generated","autogenerated",
            "automatically generated","generated automatically","this file is generated")):
        return False
    return True

def doc_hash(text):
    return hashlib.sha256(" ".join(text.split()).encode()).hexdigest()[:16]

def process_source(args):
    name, in_path, out_path = args
    seen = set()                          # per-process, within-source dedup
    kept = dropped = dup = 0
    with open(in_path, "rb") as fin, open(out_path, "wb") as fout:
        reader = zstd.ZstdDecompressor().stream_reader(fin)
        with zstd.ZstdCompressor(level=10).stream_writer(fout) as comp:
            w = io.TextIOWrapper(comp, encoding="utf-8")
            for line in tqdm(io.TextIOWrapper(reader, encoding="utf-8")):
                if not line.strip(): continue
                obj = json.loads(line)
                text = obj["text"]
                # if not starcoder_basic_filter(text):
                #     dropped += 1; continue
                if not tex_filter(text): #FOR TEX SMALLER FILTER
                    dropped+=1
                h = doc_hash(text)
                if h in seen:
                    dup += 1; continue
                seen.add(h)
                w.write(json.dumps({"text": text, "src": name, "id": h}, ensure_ascii=False) + "\n")
                kept += 1
            w.flush()
    return name, kept, dropped, dup

if __name__ == "__main__":
    base = "raw_corpus_optimized"
    # jobs = [(n, f"{base}/stack_v1_{n.split('_')[1]}.jsonl.zst", f"{base}/{n}_dedup.jsonl.zst")
    #         for n in ["stack_python","stack_cpp","stack_tex","stack_sql"]]
    jobs = [(n, f"{base}/stack_v1_{n.split('_')[1]}.jsonl.zst", f"{base}/{n}_dedup.jsonl.zst")
        for n in ["stack_tex"]]
    with ProcessPoolExecutor(max_workers=1) as ex:
        for name, kept, dropped, dup in ex.map(process_source, jobs):
            print(f"{name}: kept {kept}, filtered {dropped}, dup {dup}")